controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

goodsPage:
    path: /goodsPage/{id}
    controller: App\Controller\MainController::goodsPage
